const descriptions = {								
    anchor	:{	description:"	Gives 4 more when in a corner.	", payout:"	1	", rarity:"	Common	"},
    banana	:{	description:"	Adds when destroyed.	", payout:"	1	", rarity:"	Common	"},
    banana_peel	:{	description:"	Destroys adjacent . Destroys itself afterwards.	", payout:"	1	", rarity:"	Common	"},
    bee	:{	description:"	Adjacent and give 2x more . Gives 1 more for each adjacent or .	", payout:"	1	", rarity:"	Common	"},
    beer	:{	description:"		", payout:"	1	", rarity:"	Common	"},
    bounty_hunter	:{	description:"	Destroys adjacent . Gives 20 for each destroyed.	", payout:"	1	", rarity:"	Common	"},
    bubble	:{	description:"	Destroys itself after giving 3 times.	", payout:"	2	", rarity:"	Common	"},
    candy	:{	description:"		", payout:"	1	", rarity:"	Common	"},
    cat	:{	description:"	Destroys adjacent . Gives 9 for each destroyed.	", payout:"	1	", rarity:"	Common	"},
    cheese	:{	description:"		", payout:"	1	", rarity:"	Common	"},
    cherry	:{	description:"		", payout:"	1	", rarity:"	Common	"},
    coal	:{	description:"	Transforms into after 20 spins.	", payout:"	0	", rarity:"	Common	"},
    coin	:{	description:"		", payout:"	1	", rarity:"	Common	"},
    crab	:{	description:"	Gives 3 more for each other in the same row.	", payout:"	1	", rarity:"	Common	"},
    crow	:{	description:"	Gives -3 every 4 spins.	", payout:"	2	", rarity:"	Common	"},
    cultist	:{	description:"	Gives 1 more for each other . Gives 1 more if there are at least 3 .	", payout:"	0	", rarity:"	Common	"},
    dog	:{	description:"	Gives 2 more if adjacent to or . This effect only applies once per spin.	", payout:"	1	", rarity:"	Common	"},
    dwarf	:{	description:"	Destroys adjacent and . Gives equal to 10x the value of symbols destroyed this way.	", payout:"	1	", rarity:"	Common	"},
    egg	:{	description:"	Has a 10% chance to transform into .	", payout:"	1	", rarity:"	Common	"},
    flower	:{	description:"		", payout:"	1	", rarity:"	Common	"},
    gambler	:{	description:"	Gives ? when destroyed. " ?" increases by 2 each spin. Destroys itself when or rolls or .	", payout:"	1	", rarity:"	Common	"},
    goldfish	:{	description:"	Destroys adjacent . Gives 15 for each destroyed.	", payout:"	1	", rarity:"	Common	"},
    goose	:{	description:"	Has a 1% chance of adding .	", payout:"	1	", rarity:"	Common	"},
    key	:{	description:"	Destroys adjacent and . Destroys itself afterwards.	", payout:"	1	", rarity:"	Common	"},
    light_bulb	:{	description:"	Adjacent and give 2x more . Destroys itself after making other symbols give additional 5 times.	", payout:"	1	", rarity:"	Common	"},
    lockbox	:{	description:"	Gives 15 when destroyed.	", payout:"	1	", rarity:"	Common	"},
    magpie	:{	description:"	Gives 9 every 4 spins.	", payout:"	-1	", rarity:"	Common	"},
    milk	:{	description:"		", payout:"	1	", rarity:"	Common	"},
    miner	:{	description:"	Destroys adjacent and . Gives 20 for each and destroyed.	", payout:"	1	", rarity:"	Common	"},
    monkey	:{	description:"	Destroys adjacent and . Gives equal to 6x the value of symbols destroyed this way.	", payout:"	1	", rarity:"	Common	"},
    mouse	:{	description:"	Destroys adjacent . Gives 20 for each destroyed.	", payout:"	1	", rarity:"	Common	"},
    ore	:{	description:"	Adds or when destroyed.	", payout:"	1	", rarity:"	Common	"},
    owl	:{	description:"	Gives 1 every 3 spins.	", payout:"	1	", rarity:"	Common	"},
    oyster	:{	description:"	Has a 20% chance of adding . Adds when removed.	", payout:"	1	", rarity:"	Common	"},
    pearl	:{	description:"		", payout:"	1	", rarity:"	Common	"},
    present	:{	description:"	Destroys itself after 12 spins. Gives 10 when destroyed.	", payout:"	0	", rarity:"	Common	"},
    seed	:{	description:"	Has a 25% chance to grow into or .	", payout:"	1	", rarity:"	Common	"},
    shiny_pebble	:{	description:"	You are 1.1x more likely to find Uncommon, Rare, and Very Rare symbols.	", payout:"	1	", rarity:"	Common	"},
    snail	:{	description:"	Gives 5 every 4 spins.	", payout:"	0	", rarity:"	Common	"},
    three-sided_die	:{	description:"	Gives between 1 and 3 randomly.	", payout:"	?	", rarity:"	Common	"},
    toddler	:{	description:"	Destroys adjacent and . Gives 6 for each and destroyed.	", payout:"	1	", rarity:"	Common	"},
    turtle	:{	description:"	Gives 4 every 3 spins.	", payout:"	0	", rarity:"	Common	"},
    urn	:{	description:"	Adds when destroyed.	", payout:"	1	", rarity:"	Common	"},
    bar_of_soap	:{	description:"	Adds each spin. Destroys itself after giving 3 times.	", payout:"	1	", rarity:"	Uncommon	"},
    bear	:{	description:"	Destroys adjacent . Gives 40 for each destroyed.	", payout:"	2	", rarity:"	Uncommon	"},
    big_ore	:{	description:"	Adds 2 or when destroyed.	", payout:"	2	", rarity:"	Uncommon	"},
    big_urn	:{	description:"	Adds 2 when destroyed.	", payout:"	2	", rarity:"	Uncommon	"},
    billionaire	:{	description:"	Adjacent and give 2x more . Gives 39 when destroyed.	", payout:"	0	", rarity:"	Uncommon	"},
    bronze_arrow	:{	description:"	Points a random direction. Symbols that are pointed to give 2x more . Destroys that are pointed to.	", payout:"	0	", rarity:"	Uncommon	"},
    buffing_capsule	:{	description:"	Destroys itself. Adjacent symbols give 2x more .	", payout:"	0	", rarity:"	Uncommon	"},
    chemical_seven	:{	description:"	Destroys itself. Gives 7 and adds 1 item when destroyed.	", payout:"	0	", rarity:"	Uncommon	"},
    chick	:{	description:"	Has a 10% chance to grow into .	", payout:"	1	", rarity:"	Uncommon	"},
    clubs	:{	description:"	Adjacent and give 1 more. Gives 1 more if there are at least 3 or .	", payout:"	1	", rarity:"	Uncommon	"},
    coconut	:{	description:"	Adds 2 when destroyed.	", payout:"	1	", rarity:"	Uncommon	"},
    coconut_half	:{	description:"		", payout:"	2	", rarity:"	Uncommon	"},
    diamonds	:{	description:"	Adjacent and give 1 more. Gives 1 more if there are at least 3 or .	", payout:"	1	", rarity:"	Uncommon	"},
    essence_capsule	:{	description:"	Destroys itself. Gives 1 when destroyed	", payout:"	-12	", rarity:"	Uncommon	"},
    five-sided_die	:{	description:"	Gives between 1 and 5 randomly.	", payout:"	?	", rarity:"	Uncommon	"},
    golem	:{	description:"	Destroys itself after 5 spins. Adds 5 when destroyed.	", payout:"	0	", rarity:"	Uncommon	"},
    hearts	:{	description:"	Adjacent and give 1 more. Gives 1 more if there are at least 3 or .	", payout:"	1	", rarity:"	Uncommon	"},
    hex_of_destruction	:{	description:"	Has a 30% chance to Destroy an adjacent symbol.	", payout:"	3	", rarity:"	Uncommon	"},
    hex_of_draining	:{	description:"	Has a 30% chance to make an adjacent symbol give 0.	", payout:"	3	", rarity:"	Uncommon	"},
    hex_of_emptiness	:{	description:"	Has a 30% chance of forcing you to skip the symbols you can add after a spin.	", payout:"	3	", rarity:"	Uncommon	"},
    hex_of_hoarding	:{	description:"	Has a 30% chance of forcing you to add a symbol after this spin.	", payout:"	3	", rarity:"	Uncommon	"},
    hex_of_midas	:{	description:"	Has a 30% chance of adding .	", payout:"	3	", rarity:"	Uncommon	"},
    hex_of_tedium	:{	description:"	You are 1.3x less likely to find Uncommon, Rare, and Very Rare symbols.	", payout:"	3	", rarity:"	Uncommon	"},
    hex_of_thievery	:{	description:"	Has a 30% chance to take 6.	", payout:"	3	", rarity:"	Uncommon	"},
    hooligan	:{	description:"	Destroys adjacent and . Gives 6 for each and destroyed.	", payout:"	2	", rarity:"	Uncommon	"},
    hustling_capsule	:{	description:"	Destroys itself. Adds 1 item when destroyed.	", payout:"	-7	", rarity:"	Uncommon	"},
    item_capsule	:{	description:"	Destroys itself. Adds 1 Common item when destroyed.	", payout:"	0	", rarity:"	Uncommon	"},
    jellyfish	:{	description:"	Gives 1 when removed.	", payout:"	2	", rarity:"	Uncommon	"},
    lucky_capsule	:{	description:"	Destroys itself. At least 1 of the symbols to add after this spin will be Rare or better.	", payout:"	0	", rarity:"	Uncommon	"},
    matryoshka_doll	:{	description:"	Destroys itself after 3 spins. Adds when destroyed.	", payout:"	0	", rarity:"	Uncommon	"},
    ninja	:{	description:"	Gives 1 less for each other .	", payout:"	2	", rarity:"	Uncommon	"},
    orange	:{	description:"		", payout:"	2	", rarity:"	Uncommon	"},
    peach	:{	description:"	Adds when destroyed.	", payout:"	2	", rarity:"	Uncommon	"},
    piñata	:{	description:"	Adds 7 when destroyed.	", payout:"	1	", rarity:"	Uncommon	"},
    pufferfish	:{	description:"	Gives 1 when removed.	", payout:"	2	", rarity:"	Uncommon	"},
    rabbit	:{	description:"	Permanently gives 2 more after giving 10 times.	", payout:"	1	", rarity:"	Uncommon	"},
    rabbit_fluff	:{	description:"	You are 1.2x more likely to find Uncommon, Rare, and Very Rare symbols.	", payout:"	2	", rarity:"	Uncommon	"},
    rain	:{	description:"	Adjacent give 2x more . Adjacent are 50% more likely to grow.	", payout:"	2	", rarity:"	Uncommon	"},
    removal_capsule	:{	description:"	Destroys itself. Gives 1 when destroyed.	", payout:"	0	", rarity:"	Uncommon	"},
    reroll_capsule	:{	description:"	Destroys itself. Gives 1 when destroyed.	", payout:"	0	", rarity:"	Uncommon	"},
    safe	:{	description:"	Gives 30 when destroyed.	", payout:"	1	", rarity:"	Uncommon	"},
    sand_dollar	:{	description:"	Gives 10 when removed.	", payout:"	2	", rarity:"	Uncommon	"},
    sapphire	:{	description:"		", payout:"	2	", rarity:"	Uncommon	"},
    sloth	:{	description:"	Gives 4 every 2 spins.	", payout:"	0	", rarity:"	Uncommon	"},
    spades	:{	description:"	Adjacent and give 1 more. Gives 1 more if there are at least 3 or .	", payout:"	1	", rarity:"	Uncommon	"},
    target	:{	description:"	Gives 10 when destroyed.	", payout:"	2	", rarity:"	Uncommon	"},
    tedium_capsule	:{	description:"	Destroys itself. Gives 5 when destroyed. At least 1 of the symbols to add after this spin will be Common.	", payout:"	0	", rarity:"	Uncommon	"},
    thief	:{	description:"	Gives ? when destroyed. " ?" increases by 4 each spin.	", payout:"	-1	", rarity:"	Uncommon	"},
    time_capsule	:{	description:"	Destroys itself. Adds 1 symbol that was destroyed this game when destroyed. Cannot add .	", payout:"	0	", rarity:"	Uncommon	"},
    void_creature	:{	description:"	Adjacent give 1 more. Destroys itself if adjacent to 0 . Gives 8 when destroyed.	", payout:"	0	", rarity:"	Uncommon	"},
    void_fruit	:{	description:"	Adjacent give 1 more. Destroys itself if adjacent to 0 . Gives 8 when destroyed.	", payout:"	0	", rarity:"	Uncommon	"},
    void_stone	:{	description:"	Adjacent give 1 more. Destroys itself if adjacent to 0 . Gives 8 when destroyed.	", payout:"	0	", rarity:"	Uncommon	"},
    wealthy_capsule	:{	description:"	Destroys itself. Gives 10 when destroyed.	", payout:"	0	", rarity:"	Uncommon	"},
    wine	:{	description:"	Permanently gives 1 more after giving 8 times.	", payout:"	2	", rarity:"	Uncommon	"},
    wolf	:{	description:"		", payout:"	2	", rarity:"	Uncommon	"},
    amethyst	:{	description:"	Whenever another symbol makes this symbol give additional , this symbol permanently gives 1 more.	", payout:"	1	", rarity:"	Rare	"},
    apple	:{	description:"		", payout:"	3	", rarity:"	Rare	"},
    bartender	:{	description:"	Has a 10% chance of adding or .	", payout:"	3	", rarity:"	Rare	"},
    beastmaster	:{	description:"	Adjacent and give 2x more .	", payout:"	2	", rarity:"	Rare	"},
    beehive	:{	description:"	Has a 10% chance of adding .	", payout:"	3	", rarity:"	Rare	"},
    card_shark	:{	description:"	Adjacent and are .	", payout:"	3	", rarity:"	Rare	"},
    chef	:{	description:"	Adjacent and give 2x more .	", payout:"	2	", rarity:"	Rare	"},
    chicken	:{	description:"	Has a 5% chance of adding . Has a 1% chance of adding .	", payout:"	2	", rarity:"	Rare	"},
    comedian	:{	description:"	Adjacent and give 3x more .	", payout:"	3	", rarity:"	Rare	"},
    cow	:{	description:"	Has a 15% chance of adding .	", payout:"	3	", rarity:"	Rare	"},
    dame	:{	description:"	Adjacent and give 2x more . Destroys adjacent . Gives 40 for each destroyed.	", payout:"	2	", rarity:"	Rare	"},
    diver	:{	description:"	Removes adjacent and . Permanently gives 1 for each symbol removed.	", payout:"	2	", rarity:"	Rare	"},
    dove	:{	description:"	If an adjacent symbol would be destroyed, instead it isn't, and this symbol permanently gives 1 more.	", payout:"	2	", rarity:"	Rare	"},
    emerald	:{	description:"	Gives 1 more if there are at least 2 .	", payout:"	3	", rarity:"	Rare	"},
    farmer	:{	description:"	Adjacent and give 2x more . Adjacent are 50% more likely to grow.	", payout:"	2	", rarity:"	Rare	"},
    frozen_fossil	:{	description:"	Destroys itself after 20 spins. The amount of spins needed is reduced by 5 for each and destroyed or removed this game. Adds when destroyed.	", payout:"	0	", rarity:"	Rare	"},
    general_zaroff	:{	description:"	Destroys adjacent and . Gives 25 for each symbol destroyed.	", payout:"	1	", rarity:"	Rare	"},
    geologist	:{	description:"	Destroys adjacent and . Permanently gives 1 for each symbol destroyed.	", payout:"	2	", rarity:"	Rare	"},
    golden_egg	:{	description:"		", payout:"	4	", rarity:"	Rare	"},
    honey	:{	description:"		", payout:"	3	", rarity:"	Rare	"},
    joker	:{	description:"	Adjacent and give 2x more .	", payout:"	3	", rarity:"	Rare	"},
    king_midas	:{	description:"	Adds each spin. Adjacent give 3x more .	", payout:"	1	", rarity:"	Rare	"},
    magic_key	:{	description:"	Destroys adjacent and . Symbols destroyed this way give 3x more . Destroys itself afterward.	", payout:"	2	", rarity:"	Rare	"},
    martini	:{	description:"		", payout:"	3	", rarity:"	Rare	"},
    mine	:{	description:"	Adds each spin. Destroys itself after giving 4 times. Adds 1 item when destroyed.	", payout:"	4	", rarity:"	Rare	"},
    moon	:{	description:"	Adjacent and give 3x more . Adds 3 when destroyed.	", payout:"	3	", rarity:"	Rare	"},
    mrs._fruit	:{	description:"	Destroys adjacent and . Permanently gives 1 for each symbol destroyed.	", payout:"	2	", rarity:"	Rare	"},
    omelette	:{	description:"	Gives 2 more if adjacent to or . This effect only applies once per spin.	", payout:"	3	", rarity:"	Rare	"},
    pear	:{	description:"	Whenever another symbol makes this symbol give additional , this symbol permanently gives 1 more.	", payout:"	1	", rarity:"	Rare	"},
    robin_hood	:{	description:"	Gives 25 every 4 spins. Adjacent and give 3 more. Destroys adjacent and . Gives 15 for each and destroyed.	", payout:"	-4	", rarity:"	Rare	"},
    ruby	:{	description:"	Gives 1 more if there are at least 2 .	", payout:"	3	", rarity:"	Rare	"},
    silver_arrow	:{	description:"	Points a random direction. Symbols that are pointed to give 3x more . Destroys that are pointed to.	", payout:"	0	", rarity:"	Rare	"},
    spirit	:{	description:"	Destroys itself after giving 4 times.	", payout:"	6	", rarity:"	Rare	"},
    strawberry	:{	description:"	Gives 1 more if there are at least 2 .	", payout:"	3	", rarity:"	Rare	"},
    sun	:{	description:"	Adjacent give 5x more . Adjacent are 50% more likely to grow.	", payout:"	3	", rarity:"	Rare	"},
    tomb	:{	description:"	Has a 6% chance of adding . Adds 4 when destroyed.	", payout:"	3	", rarity:"	Rare	"},
    treasure_chest	:{	description:"	Gives 50 when destroyed.	", payout:"	2	", rarity:"	Rare	"},
    witch	:{	description:"	Adjacent and give 2x more .	", payout:"	2	", rarity:"	Rare	"},
    diamond	:{	description:"	Gives 1 more for each other .	", payout:"	5	", rarity:"	Very Rare	"},
    eldritch_creature	:{	description:"	Destroys and . Gives 1 for each and destroyed or removed this game.	", payout:"	4	", rarity:"	Very Rare	"},
    golden_arrow	:{	description:"	Points a random direction. Symbols that are pointed to give 4x more . Destroys that are pointed to.	", payout:"	0	", rarity:"	Very Rare	"},
    highlander	:{	description:"	There can be only 1 .	", payout:"	6	", rarity:"	Very Rare	"},
    mega_chest	:{	description:"	Gives 100 when destroyed.	", payout:"	3	", rarity:"	Very Rare	"},
    midas_bomb	:{	description:"	Destroys itself and all adjacent symbols. Symbols destroyed this way give equal to 7x their value.	", payout:"	0	", rarity:"	Very Rare	"},
    pirate	:{	description:"	Destroys adjacent and . Permanently gives 1 for each symbol destroyed.	", payout:"	2	", rarity:"	Very Rare	"},
    watermelon	:{	description:"	Gives 1 more for each other .	", payout:"	4	", rarity:"	Very Rare	"},
    wildcard	:{	description:"	Gives equal to the highest value among adjacent symbols.	", payout:"	?	", rarity:"	Very Rare	"},
    dud	:{	description:"	Destroys itself after 33 spins. Cannot be removed.	", payout:"	0	", rarity:"	Special	"},
    empty	:{	description:"		", payout:"	0	", rarity:"	Special	"},
    matryoshka_doll_2	:{	description:"	Destroys itself after 5 spins. Adds when destroyed.	", payout:"	1	", rarity:"	Special	"},
    matryoshka_doll_3	:{	description:"	Destroys itself after 7 spins. Adds when destroyed.	", payout:"	2	", rarity:"	Special	"},
    matryoshka_doll_4	:{	description:"	Destroys itself after 9 spins. Adds when destroyed.	", payout:"	3	", rarity:"	Special	"},
    matryoshka_doll_5	:{	description:"		", payout:"	4	", rarity:"	Special	"},
    missing	:{	description:"		", payout:"	0	", rarity:"	Special	"},
    }								